const galleryData = [
  {
    title: "Brushstrokes of Gratitude",
    category: "Tokens of Honour",
    coverImage: require('./Brushstrokes_of_Gratitude/1.jpg'),
    images: [
      require('./Brushstrokes_of_Gratitude/1.jpg'),
      require('./Brushstrokes_of_Gratitude/2.png'),
      require('./Brushstrokes_of_Gratitude/3.jpg'),
      require('./Brushstrokes_of_Gratitude/4.png'),
      require('./Brushstrokes_of_Gratitude/5.jpg'),
      require('./Brushstrokes_of_Gratitude/6.png'),
      require('./Brushstrokes_of_Gratitude/7.jpg'),
      require('./Brushstrokes_of_Gratitude/8.png'),
      require('./Brushstrokes_of_Gratitude/9.jpg'),
      require('./Brushstrokes_of_Gratitude/10.jpg'),
    ],
  },
   
  {
    title: "Portraits",
    category: "Portraits",
    coverImage: require('./Portraits/1.jpg'),
    images: [
      require('./Portraits/1.jpg'),
      require('./Portraits/2.PNG'),
      require('./Portraits/3.jpg'),
      require('./Portraits/4.PNG'),
      require('./Portraits/5.jpg'),
      require('./Portraits/6.jpg'),
      require('./Portraits/7.jpg'),
      require('./Portraits/8.jpg'),
      require('./Portraits/9.jpg'),
      require('./Portraits/10.jpg'),
      require('./Portraits/11.jpg'),
      require('./Portraits/12.jpg'),
      require('./Portraits/13.jpg'),
      require('./Portraits/14.jpg'),
      require('./Portraits/15.jpg'),
      require('./Portraits/16.jpg'),
      require('./Portraits/17.jpg'),
      require('./Portraits/18.jpg'),
      require('./Portraits/19.jpg'),
      require('./Portraits/20.jpg'),
      require('./Portraits/21.jpg'),
      require('./Portraits/22.jpg'),
      require('./Portraits/23.jpg'),
      require('./Portraits/24.jpg'),
      require('./Portraits/25.jpg'),
      require('./Portraits/26.jpg'),
      require('./Portraits/27.JPG'),
      require('./Portraits/28.jpg'),
      require('./Portraits/29.jpg'),
      require('./Portraits/30.jpg'),
    ],
  },
  {
    title: "Speed Painting Live Performance",
    category: "Speed Painting Live Performance",
    coverImage: require('./Live_Performance/1.jpg'),
    images: [
      require('./Live_Performance/1.jpg'),
      require('./Live_Performance/3.jpg'),
      require('./Live_Performance/4.jpg'),
    ],
  },
  {
    title: "Compositions",
    category: "Compositions",
    coverImage: require('./Compositions/1.jpg'),
    images: [
      require('./Compositions/1.jpg'),
      require('./Compositions/2.jpg'),
      require('./Compositions/3.jpg'),
      require('./Compositions/4.JPG'),
      require('./Compositions/5.jpg'),
      require('./Compositions/6.jpg'),
      require('./Compositions/7.jpg'),
      require('./Compositions/8.jpg'),
      require('./Compositions/9.jpg'),
      require('./Compositions/10.jpg'),
      require('./Compositions/11.jpg'),
      require('./Compositions/12.jpg'),
      require('./Compositions/13.JPG'),
      require('./Compositions/14.JPG'),
      require('./Compositions/15.JPG'),
      require('./Compositions/16.JPG'),
      require('./Compositions/20.jpg'),
      require('./Compositions/21.jpg'),
    ],
  },
   
  {
    title: "Digital Painting",
    category: "Digital Art",
    coverImage: require('./Digital_Painting/1.jpg'),
    images: [
      require('./Digital_Painting/1.jpg'),
      require('./Digital_Painting/2.jpg'),
      require('./Digital_Painting/3.JPG'),
      require('./Digital_Painting/5.JPG'),
      require('./Digital_Painting/6.JPG'),
      require('./Digital_Painting/7.JPG'),
      require('./Digital_Painting/8.JPG'),
      require('./Digital_Painting/9.jpg'),
    ],
  },
 
 
  {
    title: "Sculpture",
    category: "Sculpture",
    coverImage: require('./Sculpture/1.jpg'),
    images: [
      require('./Sculpture/1.jpg'),
      require('./Sculpture/2.jpg'),
    ],
  },
  {
    title: "Wall Murals",
    category: "Mural Art",
    coverImage: require('./Wall_murals/1.jpg'),
    images: [
      require('./Wall_murals/1.jpg'),
      require('./Wall_murals/2.jpg'),
      require('./Wall_murals/3.webp'),
      require('./Wall_murals/4.jpg'),
      require('./Wall_murals/5.jpg'),
    ],
  },
  {
    title: "Others",
    category: "Miscellaneous",
    coverImage: require('./Others/1.jpg'),
    images: [
      require('./Others/1.jpg'),
      require('./Others/2.jpg'),
      require('./Others/3.jpg'),
      require('./Others/4.jpg'),
      require('./Others/5.jpg'),
      require('./Others/6.jpg'),
      require('./Others/7.JPG'),
      require('./Others/8.jpg'),
      require('./Others/10.jpg'),
      require('./Others/11.jpg'),
      require('./Others/12.jpg'),
      require('./Others/14.jpg'),
      require('./Others/15.jpg'),
      require('./Others/16.jpg'),
    ],
  },
];

export default galleryData;
